version: '3'
services:

  web:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: dev.txt
    restart: always
    ports:
      - 8000:8000
    env_file: .env.dist
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
