# Generated by Django 4.2.4 on 2023-08-15 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_created', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)])),
            ],
            options={
                'verbose_name_plural': 'albums',
                'ordering': ['year_created'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'artists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'songs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SongsAndAlbums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_store.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_store.song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(through='music_store.SongsAndAlbums', to='music_store.album'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music_store.artist'),
        ),
    ]
